extends Node

###
onready var mainshow = get_node("Nihilogue/MainShow")
onready var art_of_the_spy = get_node("Nihilogue/MainShow")
onready var cafe = get_node("Nihilogue/MainShow")
onready var campaneoux = get_node("Nihilogue/MainShow")
onready var casette = get_node("Nihilogue/MainShow")
onready var crossing = get_node("Nihilogue/MainShow")
onready var cultist_ascent = get_node("Nihilogue/MainShow")
onready var dark_reflections = get_node("Nihilogue/MainShow")
onready var eld_lullaby = get_node("Nihilogue/MainShow")
onready var furizalex_jingle = get_node("Nihilogue/MainShow")
onready var gloom = get_node("Nihilogue/MainShow")
onready var hunt_of_the_swanman = get_node("Nihilogue/MainShow")
onready var in_trance = get_node("Nihilogue/MainShow")
onready var inn = get_node("Nihilogue/MainShow")
onready var jakies_shop = get_node("Nihilogue/MainShow")
onready var jestermania = get_node("Nihilogue/MainShow")
onready var journeystep = get_node("Nihilogue/MainShow")
onready var neo = get_node("Nihilogue/MainShow")
onready var out_fishing = get_node("Nihilogue/MainShow")
onready var peacock = get_node("Nihilogue/MainShow")
onready var plumignas = get_node("Nihilogue/MainShow")
onready var psycillow = get_node("Nihilogue/MainShow")
onready var psycotropics = get_node("Nihilogue/MainShow")
onready var shroomsville = get_node("Nihilogue/MainShow")
onready var springfall_tempaura = get_node("Nihilogue/MainShow")
onready var thehappiestdays = get_node("Nihilogue/MainShow")
onready var toby_mushguire = get_node("Nihilogue/MainShow")
onready var willow_the_tarots = get_node("Nihilogue/MainShow")

func cease():
	var a = get_node("Nihilogue").get_children()
	a.stop()

func lower():
	$AnimationPlayer.play("lower")
	
func backhigh():
	$AnimationPlayer.play_backwards("lower")

func stop():
	#Nihilogue
	mainshow.stop()
	art_of_the_spy.stop()
	cafe.stop()
	campaneoux.stop()
	casette.stop()
	crossing.stop()
	cultist_ascent.stop()
	dark_reflections.stop()
	eld_lullaby.stop()
	furizalex_jingle.stop()
	gloom.stop()
	hunt_of_the_swanman.stop()
	in_trance.stop()
	inn.stop()
	jakies_shop.stop()
	jestermania.stop()
	journeystep.stop()
	neo.stop()
	out_fishing.stop()
	peacock.stop()
	plumignas.stop()
	psycillow.stop()
	psycotropics.stop()
	shroomsville.stop()
	springfall_tempaura.stop()
	thehappiestdays.stop()
	toby_mushguire.stop()
	willow_the_tarots.stop()
